BleCommandQueue : fix second to millisecond
xabre/xamarin-bluetooth-le pull request #533
Opened 2021-08-11 17:49 UTC by sandros06

2021-08-12 12:28 UTC, lothrop commented
This would break a lot of existing implementations.

2021-08-12 15:10 UTC, sandros06 commented
Actually the default timeout is 10 millisecond very short ! 

Becaus variable name not good or missing *1000

2021-08-12 15:12 UTC, sandros06 commented on Source/Plugin.BLE.Abstractions/Utils/BleCommandQueue.cs
> -            TimeoutInMiliSeconds = timeoutInSeconds;
Typo here

2021-08-16 07:57 UTC, Hoidi requested changes

2021-08-16 07:57 UTC, Hoidi commented on Source/Plugin.BLE.Abstractions/Utils/BleCommandQueue.cs
> +        public Task<T> EnqueueAsync<T>(Func<Task<T>> bleCommand, int timeoutInMiliSeconds = 10000)
Change all MiliSeconds to Milliseconds

2021-08-16 08:09 UTC, Hoidi requested changes

2021-08-16 08:09 UTC, Hoidi commented on Source/Plugin.BLE.Abstractions/Utils/BleCommandQueue.cs
> +        public Task<T> EnqueueAsync<T>(Func<Task<T>> bleCommand, int timeoutInMiliseconds = 10000)
Needs one more L in Milli -> Milliseconds

2021-08-22 11:21 UTC, janusw commented on Source/Plugin.BLE.Abstractions/Utils/BleCommandQueue.cs
> +                if (source != await Task.WhenAny(source, Task.Delay(TimeoutInMiliseconds)))
Another typo here, as detected by the [GH Actions build](https://github.com/xabre/xamarin-bluetooth-le/pull/533/checks?check_run_id=3393160046):

```
BleCommandQueue.cs(102,69): error CS0103: The name 'TimeoutInMiliseconds' does not exist in the current context
```

Have you ever even tried to compile this branch?!?

2021-08-23 08:07 UTC, closed without merging